# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os:
  - linux
  - osx
osx_image: beta-xcode6.1
language: R
sudo: false
cache: packages
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'