// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fillhexa
DataFrame fillhexa(DataFrame hex, double res);
RcppExport SEXP recexcavAAR_fillhexa(SEXP hexSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type hex(hexSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    __result = Rcpp::wrap(fillhexa(hex, res));
    return __result;
END_RCPP
}
// pnp
bool pnp(NumericVector vertx, NumericVector verty, float testx, float testy);
RcppExport SEXP recexcavAAR_pnp(SEXP vertxSEXP, SEXP vertySEXP, SEXP testxSEXP, SEXP testySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vertx(vertxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type verty(vertySEXP);
    Rcpp::traits::input_parameter< float >::type testx(testxSEXP);
    Rcpp::traits::input_parameter< float >::type testy(testySEXP);
    __result = Rcpp::wrap(pnp(vertx, verty, testx, testy));
    return __result;
END_RCPP
}
// pnpmulti
LogicalVector pnpmulti(NumericVector vertx, NumericVector verty, NumericVector testx, NumericVector testy);
RcppExport SEXP recexcavAAR_pnpmulti(SEXP vertxSEXP, SEXP vertySEXP, SEXP testxSEXP, SEXP testySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vertx(vertxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type verty(vertySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type testx(testxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type testy(testySEXP);
    __result = Rcpp::wrap(pnpmulti(vertx, verty, testx, testy));
    return __result;
END_RCPP
}
// posdec
DataFrame posdec(DataFrame crlist, List maplist);
RcppExport SEXP recexcavAAR_posdec(SEXP crlistSEXP, SEXP maplistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type crlist(crlistSEXP);
    Rcpp::traits::input_parameter< List >::type maplist(maplistSEXP);
    __result = Rcpp::wrap(posdec(crlist, maplist));
    return __result;
END_RCPP
}
// posdeclist
List posdeclist(List crlist, List maplist);
RcppExport SEXP recexcavAAR_posdeclist(SEXP crlistSEXP, SEXP maplistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type crlist(crlistSEXP);
    Rcpp::traits::input_parameter< List >::type maplist(maplistSEXP);
    __result = Rcpp::wrap(posdeclist(crlist, maplist));
    return __result;
END_RCPP
}
// spatiallong
DataFrame spatiallong(NumericVector x, NumericVector y, NumericMatrix z);
RcppExport SEXP recexcavAAR_spatiallong(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    __result = Rcpp::wrap(spatiallong(x, y, z));
    return __result;
END_RCPP
}
// spatialwide
List spatialwide(NumericVector x, NumericVector y, NumericVector z, int digits);
RcppExport SEXP recexcavAAR_spatialwide(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP digitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    __result = Rcpp::wrap(spatialwide(x, y, z, digits));
    return __result;
END_RCPP
}
// spitcenter
NumericVector spitcenter(DataFrame hex);
RcppExport SEXP recexcavAAR_spitcenter(SEXP hexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type hex(hexSEXP);
    __result = Rcpp::wrap(spitcenter(hex));
    return __result;
END_RCPP
}
// spitcenternat
DataFrame spitcenternat(DataFrame hex, List maplist);
RcppExport SEXP recexcavAAR_spitcenternat(SEXP hexSEXP, SEXP maplistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type hex(hexSEXP);
    Rcpp::traits::input_parameter< List >::type maplist(maplistSEXP);
    __result = Rcpp::wrap(spitcenternat(hex, maplist));
    return __result;
END_RCPP
}
// spitcenternatlist
List spitcenternatlist(List hexlist, List maplist);
RcppExport SEXP recexcavAAR_spitcenternatlist(SEXP hexlistSEXP, SEXP maplistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type hexlist(hexlistSEXP);
    Rcpp::traits::input_parameter< List >::type maplist(maplistSEXP);
    __result = Rcpp::wrap(spitcenternatlist(hexlist, maplist));
    return __result;
END_RCPP
}
